# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20210917-12df099d55'
    entrypoint: 'bash'
    dir: ./cluster/images/etcd
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - REGISTRY=gcr.io/$PROJECT_ID
      - PUSH_REGISTRY=gcr.io/$PROJECT_ID
      - IMAGE=gcr.io/$PROJECT_ID/etcd
      - BUILD_IMAGE=debian-build
      - TMPDIR=/workspace
      - HOME=/root  # for docker buildx
    args:
      - '-c'
      - |
        gcloud auth configure-docker \
        && docker buildx create --name img-builder --use \
        && docker buildx inspect --bootstrap \
        && docker run --rm --privileged linuxkit/binfmt:4ea3b9b0938cbd19834c096aa31ff475cc75d281 \
        && make all-push
