apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: foo
webhooks:
  - name: foo.samplecontroller.k8s.io
    clientConfig:
      service:
        namespace: default
        name: sample-controller-webhook-server
        path: /validate-samplecontroller-k8s-io-v1alpha1-foo
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvRENDQW9pZ0F3SUJBZ0lVZTAxbU9vMVVlYXlMRTgwTStaK1Ezc1VrNXBNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEV6QVJCZ05WQkFvVENrdDFZbVZ5Ym1WMFpYTXhDekFKQmdOVkJBc1RBa05CTVJNd0VRWURWUVFECkV3cExkV0psY201bGRHVnpNQjRYRFRJek1EY3lNREV3TURBd01Gb1hEVEk0TURjeE9ERXdNREF3TUZvd2FERUwKTUFrR0ExVUVCaE1DVlZNeER6QU5CZ05WQkFnVEJrOXlaV2R2YmpFUk1BOEdBMVVFQnhNSVVHOXlkR3hoYm1ReApFekFSQmdOVkJBb1RDa3QxWW1WeWJtVjBaWE14Q3pBSkJnTlZCQXNUQWtOQk1STXdFUVlEVlFRREV3cExkV0psCmNtNWxkR1Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3a2hCSjRENncrNVoKNDhndGdVRjI5bS9tekpRdG92bnJsSjNYOGxScDhNc2IxU1EvbkNMaFJmZUd0RHhQSVFtTFdsblhTcHRqYUpUcgp4Ukp2OEhsZ00rK2c2bHFqNTJ5Z1hobzY3TzBrSHZWN3NlNzZ1MGdLQWxiaXNWSUo1b29yTDI1b1Q3cko4Mi90CkNvbkRiK2Q4K0tmREZjV20zV2hDWWZvOVVaclVjK1kxRGRhWjRWOU1qQUc5Q29GMnBoVGNmVSszOGtiTXE3N1AKM0lCNVJjV2lKZFQxbmtqeEFmclZXN3ZJZERsN3UrbG9MZHNZcGV6SWF2TExNRGZQUHB3UjViUHBXQlQrOVhkZQpxWDJlcHNFYXNmeWwrUVVNTnNIdnIxN2F4VTFjaGVsUFIrdVlrQXRBd3BOMk9ZdHRMYStKZmhiYnhhZldCRU1OCk02b0ZIYkttTFFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVThycXAxTGxFOVRMcWxYdENkWWRoTTNPTHJONHdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUtEc3JodWZvL200MFhsc2J1ZUw4RjQ3SGt4SnBNTVU0NUlXSWVtYktyK0FRQlRDa2ZUUXZncEtNWUtHCnIzUzZTZUdma3Eva0hLUk1POXdFRlhEa0tEK0VibHd1MkxIbERLUThMZGYrTm9nMWZpNEdmbXh6TEVYek1YSkEKMXd6SmlnbnpVT0N0NGpnMFVCR0ZYSUdJQldwbnV2aUNJOVg3L25tSVBWY0RrT01aMXVKc2F0TDBJQVpvck5rcApyb3h4a3dPVFY0OVB6TVFnT3hpYXgzMWhESk5obWgvZnNqUGIvV0YzWFBvajFSTitMaXNIU2kzR0N2a3RqUVhoCjdPMis4d3hFUlc0UlBrMlcyVTdCLzViMldmOGZKSThiNytRQkI5L2o4K1oxREYwU0ozUG1IOGRrQTYrU3gyVjYKZFZ4L05MMGRvVHUwKzI4YkVKUlR5K01WWW9NPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - apiGroups: ["samplecontroller.k8s.io"]
        apiVersions: ["v1alpha1"]
        resources: ["foos"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        scope: Namespaced
    sideEffects: None
    admissionReviewVersions: ["v1"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: foo
webhooks:
  - name: foo.samplecontroller.k8s.io
    clientConfig:
      service:
        namespace: default
        name: sample-controller-webhook-server
        path: /mutate-samplecontroller-k8s-io-v1alpha1-foo
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvRENDQW9pZ0F3SUJBZ0lVZTAxbU9vMVVlYXlMRTgwTStaK1Ezc1VrNXBNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEV6QVJCZ05WQkFvVENrdDFZbVZ5Ym1WMFpYTXhDekFKQmdOVkJBc1RBa05CTVJNd0VRWURWUVFECkV3cExkV0psY201bGRHVnpNQjRYRFRJek1EY3lNREV3TURBd01Gb1hEVEk0TURjeE9ERXdNREF3TUZvd2FERUwKTUFrR0ExVUVCaE1DVlZNeER6QU5CZ05WQkFnVEJrOXlaV2R2YmpFUk1BOEdBMVVFQnhNSVVHOXlkR3hoYm1ReApFekFSQmdOVkJBb1RDa3QxWW1WeWJtVjBaWE14Q3pBSkJnTlZCQXNUQWtOQk1STXdFUVlEVlFRREV3cExkV0psCmNtNWxkR1Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3a2hCSjRENncrNVoKNDhndGdVRjI5bS9tekpRdG92bnJsSjNYOGxScDhNc2IxU1EvbkNMaFJmZUd0RHhQSVFtTFdsblhTcHRqYUpUcgp4Ukp2OEhsZ00rK2c2bHFqNTJ5Z1hobzY3TzBrSHZWN3NlNzZ1MGdLQWxiaXNWSUo1b29yTDI1b1Q3cko4Mi90CkNvbkRiK2Q4K0tmREZjV20zV2hDWWZvOVVaclVjK1kxRGRhWjRWOU1qQUc5Q29GMnBoVGNmVSszOGtiTXE3N1AKM0lCNVJjV2lKZFQxbmtqeEFmclZXN3ZJZERsN3UrbG9MZHNZcGV6SWF2TExNRGZQUHB3UjViUHBXQlQrOVhkZQpxWDJlcHNFYXNmeWwrUVVNTnNIdnIxN2F4VTFjaGVsUFIrdVlrQXRBd3BOMk9ZdHRMYStKZmhiYnhhZldCRU1OCk02b0ZIYkttTFFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVThycXAxTGxFOVRMcWxYdENkWWRoTTNPTHJONHdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUtEc3JodWZvL200MFhsc2J1ZUw4RjQ3SGt4SnBNTVU0NUlXSWVtYktyK0FRQlRDa2ZUUXZncEtNWUtHCnIzUzZTZUdma3Eva0hLUk1POXdFRlhEa0tEK0VibHd1MkxIbERLUThMZGYrTm9nMWZpNEdmbXh6TEVYek1YSkEKMXd6SmlnbnpVT0N0NGpnMFVCR0ZYSUdJQldwbnV2aUNJOVg3L25tSVBWY0RrT01aMXVKc2F0TDBJQVpvck5rcApyb3h4a3dPVFY0OVB6TVFnT3hpYXgzMWhESk5obWgvZnNqUGIvV0YzWFBvajFSTitMaXNIU2kzR0N2a3RqUVhoCjdPMis4d3hFUlc0UlBrMlcyVTdCLzViMldmOGZKSThiNytRQkI5L2o4K1oxREYwU0ozUG1IOGRrQTYrU3gyVjYKZFZ4L05MMGRvVHUwKzI4YkVKUlR5K01WWW9NPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - apiGroups: [ "samplecontroller.k8s.io" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "foos" ]
        operations: ["CREATE"]
        scope: Namespaced
    sideEffects: None
    admissionReviewVersions: ["v1"]