server:
  port: 80

ingress:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-myservicea
      annotations:
        jtthink.ingress.kubernetes.io/add-request-header: name=shenyi;age=19
        jtthink.ingress.kubernetes.io/rewrite-target: /$1
    spec:
      rules:
        - host: aabb.com
          http:
            paths:
              - path: /jtthink/{param:.*}
                backend:
                  service:
                    name: localhost
                    port:
                      number: 8080
              - path: /baidu/{param:.*}
                backend:
                  service:
                    name: www.baidu.com
                    port:
                      number: 80