/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	dbconfigv1 "github.com/shenyisyn/dbcore/pkg/apis/dbconfig/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDbConfigs implements DbConfigInterface
type FakeDbConfigs struct {
	Fake *FakeApiV1
	ns   string
}

var dbconfigsResource = schema.GroupVersionResource{Group: "api.jtthink.com", Version: "v1", Resource: "dbconfigs"}

var dbconfigsKind = schema.GroupVersionKind{Group: "api.jtthink.com", Version: "v1", Kind: "DbConfig"}

// Get takes name of the dbConfig, and returns the corresponding dbConfig object, and an error if there is any.
func (c *FakeDbConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *dbconfigv1.DbConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dbconfigsResource, c.ns, name), &dbconfigv1.DbConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dbconfigv1.DbConfig), err
}

// List takes label and field selectors, and returns the list of DbConfigs that match those selectors.
func (c *FakeDbConfigs) List(ctx context.Context, opts v1.ListOptions) (result *dbconfigv1.DbConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dbconfigsResource, dbconfigsKind, c.ns, opts), &dbconfigv1.DbConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &dbconfigv1.DbConfigList{ListMeta: obj.(*dbconfigv1.DbConfigList).ListMeta}
	for _, item := range obj.(*dbconfigv1.DbConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dbConfigs.
func (c *FakeDbConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dbconfigsResource, c.ns, opts))

}

// Create takes the representation of a dbConfig and creates it.  Returns the server's representation of the dbConfig, and an error, if there is any.
func (c *FakeDbConfigs) Create(ctx context.Context, dbConfig *dbconfigv1.DbConfig, opts v1.CreateOptions) (result *dbconfigv1.DbConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dbconfigsResource, c.ns, dbConfig), &dbconfigv1.DbConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dbconfigv1.DbConfig), err
}

// Update takes the representation of a dbConfig and updates it. Returns the server's representation of the dbConfig, and an error, if there is any.
func (c *FakeDbConfigs) Update(ctx context.Context, dbConfig *dbconfigv1.DbConfig, opts v1.UpdateOptions) (result *dbconfigv1.DbConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dbconfigsResource, c.ns, dbConfig), &dbconfigv1.DbConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dbconfigv1.DbConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDbConfigs) UpdateStatus(ctx context.Context, dbConfig *dbconfigv1.DbConfig, opts v1.UpdateOptions) (*dbconfigv1.DbConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dbconfigsResource, "status", c.ns, dbConfig), &dbconfigv1.DbConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dbconfigv1.DbConfig), err
}

// Delete takes name of the dbConfig and deletes it. Returns an error if one occurs.
func (c *FakeDbConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dbconfigsResource, c.ns, name, opts), &dbconfigv1.DbConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDbConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dbconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &dbconfigv1.DbConfigList{})
	return err
}

// Patch applies the patch and returns the patched dbConfig.
func (c *FakeDbConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *dbconfigv1.DbConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dbconfigsResource, c.ns, name, pt, data, subresources...), &dbconfigv1.DbConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*dbconfigv1.DbConfig), err
}
