resources:
    - name: jtthink_cluster_config
      "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      connect_timeout: 1s
      type: Static
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: jtthink_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 10.88.0.2
                      port_value: 80
