admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

node:
  cluster: mynode
  id: node01
dynamic_resources:
  cds_config:
    path: /etc/envoy/cds.yaml
  lds_config:
    path: /etc/envoy/lds.yaml