apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: my-istio
spec:
  profile: minimal
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  components:
    ingressGateways:
      - name: ingressgateway
        namespace: istio-system
        enabled: true
        label:
          istio: ingressgateway
        k8s:
          imagePullPolicy: IfNotPresent
          service:
            type: ClusterIP
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway