# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
steps:
  - name: 'gcr.io/k8s-testimages/gcb-docker-gcloud:v20200422-b25d964'
    entrypoint: 'bash'
    dir: ./cluster/images/etcd
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - REGISTRY=gcr.io/$PROJECT_ID
      - PUSH_REGISTRY=gcr.io/$PROJECT_ID
      - IMAGE=gcr.io/$PROJECT_ID/etcd
      - BUILD_IMAGE=debian-build
      - TMPDIR=/workspace
    args:
      - '-c'
      - |
        gcloud auth configure-docker \
        && docker run --rm --privileged linuxkit/binfmt:4ea3b9b0938cbd19834c096aa31ff475cc75d281 \
        && make all-push
